グループ数の指定とエラー表示
OJT-3G/random-grouping-app pull request #12
Opened 2022-10-21 07:00 UTC by tsubasa-nishikawa

作成に当たり以下の項目を行ったので確認をお願いします。

### **issue**
- Resolve #9

### **対応内容**
- 「グループ数」と画面の上部に表示しテキストボックスを「グループ数」の下に表示する
- テキストボックスの入力内容を変数に入れる
- 半角の自然数以外がテキストボックスに入った場合(または空白)は「1以上の整数を半角で入力してください」と赤文字で、「グループ数」とテキストボックスの間に表示する

### **動作確認内容**
- 「グループ数」とテキストボックスの表示位置が問題ないか
- テキストボックスへの入力内容が変数に入っているか確認するために、コンソールログに変数を表示する
- テキストボックスに半角の自然数をいれた場合と空白の時にエラーメッセージが出ないか
- テキストボックスに半角の自然数以外を入れたときに「1以上の整数を半角で入力してください」とエラーメッセージが赤文字で適切な位置に表示されるか

2022-10-23 23:56 UTC, rknakashima commented
以前も伝えましたが、Issueのリンクを貼ってくれると嬉しいです！
https://github.com/OJT-3G/random-grouping-app/pull/10#pullrequestreview-1148378665

2022-10-24 00:22 UTC, yk-nakamura commented
https://github.com/OJT-3G/random-grouping-app/pull/12/commits/9ab58425df9ae172739dcd6b27c60360cf12085d 
のコミットコメントから何のために加えた変更なのかが読み取れません。改善をお願いします。

2022-10-24 00:23 UTC, yk-nakamura commented
また、余計な差分が含まれていますが、レビュー依頼前に確認して余計な差分が含まれないようにしてください。

2022-10-24 10:47 UTC, yk-nakamura requested changes
いくつか気になる点コメントしたのでご確認お願いします。

2022-10-24 10:47 UTC, yk-nakamura commented on pages/index.tsx
> +  const [groupNumber, setGroupNumber] = useState('');
numberなのに文字列型なのは違和感があります。

2022-10-24 10:47 UTC, yk-nakamura commented on pages/index.tsx
> +  const onChangeTextBox = (event: { target: { value: any; }; }) => {
基本的にany型は使わないようにしましょう。
（ESLintで警告出ませんでしたかね？）

2022-10-24 10:47 UTC, yk-nakamura commented on pages/index.tsx
> +  const [message, setMessage] = useState('');
現状エラーメッセージしか格納しないつもりなのであれば`errorMessage`でも良いかもと思いました。

2022-10-24 10:47 UTC, yk-nakamura commented on pages/index.tsx
> +          <input type="text" value={groupNumber} onChange={onChangeTextBox}></input>
数値しか入れて欲しくないのであれば`type="number"`にした方が良いです。
また、ブラウザによって挙動は変わりますが`min` `max` `pattern`属性なども指定しておくと便利です。

2022-10-24 10:47 UTC, yk-nakamura commented on pages/index.tsx
> +          <input type="text" value={groupNumber} onChange={onChangeTextBox}></input>
inputタグは中身がないので `<input ~ />` と書いてほしいです。

2022-10-24 23:58 UTC, rknakashima commented on pages/index.tsx
> +        <title>random-grouping-app</title>
ここではアプリ名を指定しています？アプリ名であればハイフン込みなのに違和感を感じました。

2022-10-25 00:26 UTC, RustyNail commented on pages/index.tsx
> +  const onChangeTextBox = (event: { target: { value: any; }; }) => {
> ESLintで警告出ませんでしたかね？

@yk-nakamura さんのおっしゃる通り、LinterでPASSしていることの確認はされた方が良いかと思います。
されていないのであれば、一度Linterを走らせた方が良いと思います。
レビューアーもレビュイーもその手間が省けるので！

そして、PullRequestの**検証したこと**の冒頭に
「**LinterがPASSしていることを確認**」と書いておくのが良いかと思います！

2022-10-25 00:28 UTC, RustyNail commented on pages/index.tsx
> +    console.log(targetValue)
; セミコロンは不要ですか？

2022-10-25 01:40 UTC, tsubasa-nishikawa commented on package.json
> +    "build": "next build && next export",
リリースのための変更であるので本来であればコミットを分けること、承知しました。

2022-10-25 02:14 UTC, yk-nakamura commented on pages/index.tsx
> +    console.log(targetValue)
これもprettierなどを導入して統一されるようにしたいですね。

2022-10-25 02:23 UTC, rknakashima commented on pages/index.tsx
> +  const onChangeTextBox = (event: { target: { value: any; }; }) => {
レビュー負荷軽減のためにも、Linterでのチェックはしてもらいたいですね！

Linterの設定とLinterがPASSしていることを確認するルール設定等は次スプリントのタスクとして積むことにしようと思います。（この場では対応を見送りたいです）

@tsubasa-nishikawa `基本的にany型は使わないようにしましょう。` こちらの指摘対応のみお願いします。

2022-10-25 05:23 UTC, yk-nakamura approved these changes
LGTM

2022-10-25 05:28 UTC, tsubasa-nishikawa commented on package.json
> +    "serve": "yarn export && serve ./out",
削除しました。

2022-10-25 05:29 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +        </h1> */}
必要ないので今回は削除しました。コメントを中に書くことをあまりしていないので必要に応じてコメントアウトします。

2022-10-25 05:29 UTC, tsubasa-nishikawa commented on styles/Home.module.css
> +  line-height: 1.5; */
削除しました

2022-10-25 05:29 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +          <p className={styles.description}>グループ数</p>
「label」に変更しました。

2022-10-25 05:30 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +  const [groupNumber, setGroupNumber] = useState('');
初期値を1にしました。

2022-10-25 05:30 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +  const onChangeTextBox = (event: { target: { value: any; }; }) => {
any型を使わないようにstringに直しました

2022-10-25 05:31 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +  const [message, setMessage] = useState('');
errorMessageに変更しました。

2022-10-25 05:34 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +          <input type="text" value={groupNumber} onChange={onChangeTextBox}></input>
type="number"とし、上限下限を設定し、<input ~ />としました。

2022-10-25 05:35 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +        <title>random-grouping-app</title>
ハイフンを消しました。

2022-10-25 05:36 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +    console.log(targetValue)
セミコロンは必要だと思いました。ただ、コンソールログは確認のために書いていたものなので消しました。

2022-10-25 06:10 UTC, RustyNail commented on pages/index.tsx
> +      setErrorMessage('');
質問です。
targetValueが空でない時も setErrorMessageはされるべきなのでしょうか？

2022-10-25 06:22 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +      setErrorMessage('');
ボックスの数字を直接消す(空の時)とerrorMessageが表示されるようにしたのですが、空にした後に自然数を入力してもエラー表示が残ってしまうのでtargetValueが空でない時の処理を書いておきました。

2022-10-25 07:03 UTC, rknakashima approved these changes
LGTMです

2022-10-25 07:17 UTC, RustyNail approved these changes
LGTM！！

2022-10-25 07:46 UTC, merged