グループ分け結果を表示する(グループ数とグループ分けに制約あり)
OJT-3G/random-grouping-app pull request #14
Opened 2022-10-31 05:44 UTC by tsubasa-nishikawa

作成に当たり以下の項目を行ったので確認をお願いします。

### **issue**
- Resolve #7

### **対応内容**
- メンバーのダミーデータが12要素入った配列を用意した
- 配列の要素を4人ずつ3グループに分け表に表示した
- 表のスタイルを #7 の画像に合わせた

### **動作確認内容**
- 表がグループ数の入力欄の下に表示されるか
- 12人の名前が表示されているか
- スタイルが #7 と比べ大きく違っていないか

2022-10-31 07:08 UTC, yk-nakamura requested changes

2022-10-31 07:08 UTC, yk-nakamura commented on styles/Home.module.css
> +.tableHead {
class名はケバブケースにしましょうか。
（キャメルケースが絶対ダメってわけじゃないんですが、一般的なのはケバブケースだと思っているので。）

2022-11-01 23:00 UTC, yk-nakamura commented on styles/Home.module.css
> +.tableHead {
あーごめんなさい。CSS Modulesだったので呼び出し側が書きづらくなっちゃいましたね。
あまり考えず指摘してしまって申し訳ないですが、元に戻していただけると嬉しいです。。。

2022-11-01 23:00 UTC, yk-nakamura commented on pages/index.tsx
> +  let groupMember = ['ふじい','あらかわ','あさい','いいだ','いしざき','なかむら','なかしま','にしかわ','おぎや','おおさか','さんのう','たなか'];
確認しました。

2022-11-01 23:01 UTC, yk-nakamura commented on pages/index.tsx
> +
https://github.com/OJT-3G/random-grouping-app/pull/14/commits/ede62092b7d7ac3c9bb65c712c73607bb42d7fc6 で空行削除以外の差分が出ているのが気になります。改行コードの変更でもしたんでしょうか？

2022-11-01 23:07 UTC, yk-nakamura commented
![image](https://user-images.githubusercontent.com/8165062/199358473-1c1a6eaa-bb98-4d75-95c9-a472c01ec233.png)
コミットコメントは**Why**がわかるように書いてください。
現状はWhatが書かれていますが、背景がわからないので後々見返した際に「なぜこの変更を入れたんだろう？」となってしまいます。

また、プルリクエストをマージするときにsquashマージするので`(グループ分け結果の表示の修正)`は不要です。（developへのマージ時に1つのコミットにまとめられます。）

2022-11-02 04:05 UTC, RustyNail commented on pages/index.tsx
> +                <tr><td>{groupMember[0]}</td><td>{groupMember[1]}</td><td>{groupMember[2]}</td></tr>
```
 <tr>
   <td>{groupMember[0]}</td>
   <td>{groupMember[1]}</td>
   <td>{groupMember[2]}</td>
 </tr>
  <tr>
   <td>{groupMember[3]}</td>
   <td>{groupMember[4]}</td>
   <td>{groupMember[5]}</td>
 </tr>
  <tr>
   <td>{groupMember[6]}</td>
   <td>{groupMember[7]}</td>
   <td>{groupMember[8]}</td>
 </tr>
  <tr>
   <td>{groupMember[9]}</td>
   <td>{groupMember[10]}</td>
   <td>{groupMember[11]}</td>
 </tr>
 ```
 としておくと見やすいのでは

2022-11-02 04:08 UTC, RustyNail commented on pages/index.tsx
> +              <thead className={styles['table-head']}>
インデント(スペース2つ)にされたほうが良いのでは

2022-11-02 04:11 UTC, RustyNail commented on pages/index.tsx
> +import type { NextPage } from 'next'
この行や以降の行も変更ないと思うのですが、変更差分に入っているのは何かを変えられたのでしょうか？
差分が多いとレビュアーがみる対象も多くなることを考慮されたほうが良いです。

2022-11-02 04:26 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +
改行コードが知らないうちに「CRLF」になってしまっていました。何かの作業で変更されてしまったんだと思います。改行コードを統一するため「LF」に変更しました。

[コミット内容](https://github.com/OJT-3G/random-grouping-app/commit/aa6a99a743ad3b88498163f432b14b8b3bf73edf)

2022-11-02 04:28 UTC, tsubasa-nishikawa commented on styles/Home.module.css
> +.tableHead {
呼び出し側が書きづらくなるということで、ケバブケースに変更したところをキャメルケースに戻しました。

[コミット内容](https://github.com/OJT-3G/random-grouping-app/commit/25b462f139486da2f0a459dc1fdf419f663703d5)

2022-11-02 04:29 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +                <tr><td>{groupMember[0]}</td><td>{groupMember[1]}</td><td>{groupMember[2]}</td></tr>
確かにそちらの方が見やすいですね。テーブルの要素を見やすく開業しました。

[コミット内容](https://github.com/OJT-3G/random-grouping-app/commit/d974bcefdd49e703a210caa9c3b99aae54930f45)

2022-11-02 04:31 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +              <thead className={styles['table-head']}>
統一できていない箇所の指摘ありがとうございます。インデントをスペース2つに統一しました。
以下のコミット内容は[他の見た目に関する修正](https://github.com/OJT-3G/random-grouping-app/pull/14#discussion_r1011149439)とまとめています。

[コミット内容](https://github.com/OJT-3G/random-grouping-app/commit/d974bcefdd49e703a210caa9c3b99aae54930f45)

2022-11-02 04:35 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +import type { NextPage } from 'next'
[こちら](https://github.com/OJT-3G/random-grouping-app/pull/14#discussion_r1010978670)で対応しました。
知らないうちに改行コードを触ってしまったようです。差分を確認してからコミットをする習慣がついておらず気づけなかったので、13:00以降のコミット内容(修正)では差分を確認してからコミットするように気を付けました。

2022-11-02 04:37 UTC, RustyNail commented
To : @tsubasa-nishikawa さん ( cc : @yk-nakamura さん @rknakashima さん )

<img width="1100" alt="スクリーンショット 2022-11-02 13 34 26" src="https://user-images.githubusercontent.com/821981/199398566-9c7d055b-403f-4cca-8ff2-f25aa223ca0b.png">

私の手元で動かしてみて、期待通りのビューが表示されていることを確認しました。
できれば、冒頭で書かれている動作確認項目のところにこのような証跡を載せておくほうがレビュアーには親切だと思います。

2022-11-02 04:41 UTC, yk-nakamura commented on pages/index.tsx
> +
確認しました。

2022-11-02 04:42 UTC, yk-nakamura commented on styles/Home.module.css
> +.tableHead {
すみません。ありがとうございます。

2022-11-02 04:44 UTC, yk-nakamura approved these changes
中村指摘分に対してはLGTMです

2022-11-02 05:24 UTC, RustyNail commented
前回のPRで @yk-nakamura さんが 指摘されていましたが、ESlintで検出されたエラーは修正された上で
レビューを開始したほうが良いです。
今回の変更したファイルだけでもまず直されたほうが良いと思います。

以下、ESlintの実行結果載せておきます。参考までに

```
180:random-grouping-app $ npx eslint pages/index.tsx 

pages/index.tsx
   1:1    error  Definition for rule '@typescript-eslint/no-unused-vars' was not found  @typescript-eslint/no-unused-vars
   3:33   error  Extra semicolon                                                        semi
   6:30   error  Block must not be padded by blank lines                                padded-blocks
   8:52   error  Extra semicolon                                                        semi
   9:55   error  Extra semicolon                                                        semi
  12:29   error  A space is required after ','                                          comma-spacing
  12:36   error  A space is required after ','                                          comma-spacing
  12:42   error  A space is required after ','                                          comma-spacing
  12:48   error  A space is required after ','                                          comma-spacing
  12:55   error  A space is required after ','                                          comma-spacing
  12:62   error  A space is required after ','                                          comma-spacing
  12:69   error  A space is required after ','                                          comma-spacing
  12:76   error  A space is required after ','                                          comma-spacing
  12:82   error  A space is required after ','                                          comma-spacing
  12:89   error  A space is required after ','                                          comma-spacing
  12:96   error  A space is required after ','                                          comma-spacing
  12:103  error  Extra semicolon                                                        semi
  15:43   error  Extra semicolon                                                        semi
  16:42   error  Extra semicolon                                                        semi
  19:40   error  Extra semicolon                                                        semi
  21:26   error  Extra semicolon                                                        semi

✖ 21 problems (21 errors, 0 warnings)
  20 errors and 0 warnings potentially fixable with the `--fix` option.
```

2022-11-04 01:18 UTC, rknakashima commented
> 前回のPRで @yk-nakamura さんが 指摘されていましたが、ESlintで検出されたエラーは修正された上で レビューを開始したほうが良いです。 今回の変更したファイルだけでもまず直されたほうが良いと思います。

@RustyNail すみません、ESLint のエラーですが #19 で対応を検討したいためこのPRでは一旦後回しとしたいです。

2022-11-07 02:05 UTC, RustyNail approved these changes
#19 でESLintは対応される旨、承知しました。
LGTM

2022-11-07 02:29 UTC, merged