ESLintとPretterを導入し既存コードを整形する
OJT-3G/random-grouping-app pull request #20
Opened 2022-11-07 07:08 UTC by tsubasa-nishikawa

以下の項目を行ったので確認をお願いします。

### **issue**
- Resolve #19

### **対応内容**
- コーチャー(代理)と一緒にESLintの導入を行った
- コーチャー(代理)と一緒にPrettierの導入を行った
- 既存コードを自動整形した

### **動作確認内容**
- 自動整形コマンドをターミナルにうち「No ESLint warnings or errors」が出る

2022-11-07 08:29 UTC, RustyNail commented
Teamsの方でコメントさせていただいた通り、READMEヘ記載をいただき次第
私も手元で確認してみます。
その確認結果を以てApproveさせていただきます！

2022-11-08 02:47 UTC, tsubasa-nishikawa commented
> Teamsの方でコメントさせていただいた通り、READMEヘ記載をいただき次第 私も手元で確認してみます。 その確認結果を以てApproveさせていただきます！

[コミット](https://github.com/OJT-3G/random-grouping-app/pull/20/commits/9a510461282304e0c8ad2e90d3cf84800ee0b64a)しました。

何のアプリなのか、どのように起動するのか等がわかるようにREADMEの作成を行いました。

2022-11-08 04:20 UTC, yk-nakamura requested changes
LGTMしてましたがREADMEで気になる箇所があったのでコメントしました。

2022-11-08 04:20 UTC, yk-nakamura commented on README.md
> +$ npm run dev
yarnコマンドを使う方針で統一してほしいです

2022-11-08 04:20 UTC, yk-nakamura commented on README.md
> +ESLint でコードの静的解析を行う
ESLintだけではないので、下記のようにしたらいかがでしょうか？
```suggestion
ESLint および Prettier でコードの静的解析を行う
```

2022-11-08 05:32 UTC, RustyNail approved these changes
LGTM

2022-11-08 05:37 UTC, RustyNail commented on README.md
> +ESLint でコードの静的解析を行う
@yk-nakamura さん

( @tsubasa-nishikawa さんとペアプロ中なので代理でコメント入力しています )
`$ yarn lint` で `$ yarn lint:eslint && yarn lint:prettier` が実行されるので両方ですね！

こちら、動作することを確認済みです。
```
$ yarn lint
yarn run v1.6.0
$ yarn lint:eslint && yarn lint:prettier
$ next lint
✔ No ESLint warnings or errors
$ prettier --check --ignore-unknown "**/*"
Checking formatting...
All matched files use Prettier code style!
✨  Done in 8.03s.

```

2022-11-08 05:39 UTC, RustyNail commented on README.md
> +$ npm run dev
@yk-nakamura さん

( @tsubasa-nishikawa さんとペアプロ中なので代理でコメント入力しています )

`$ npm run dev`  => `$ yarn dev` に変更しました。

2022-11-08 05:42 UTC, tsubasa-nishikawa commented on README.md
> +$ npm run dev
yarn devで実行し、同様の結果を得られることを確認しました。

```
$ yarn dev
yarn run v1.22.19
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 510 ms (173 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 314 ms (181 modules)
```

2022-11-08 05:46 UTC, yk-nakamura approved these changes
修正ありがとうございます。LGTM

2022-11-08 05:48 UTC, merged