メンバーの調整のため、メンバー一覧からメンバーを削除出来るようにした
OJT-3G/random-grouping-app pull request #33
Opened 2022-11-25 04:16 UTC by tsubasa-nishikawa

- Resolve #1
- 希望納期:11/28
- レビュアー: @rknakashima @yk-nakamura @RustyNail
- 仕様書: 無し

# 対応内容
### 機能追加
 - メンバー調整時にメンバーを削除できるようにした

### バグ修正
- 無し

# 動作確認内容
1.メンバー一覧の削除ボタン押下後、メンバー一覧とグループ分け結果から削除したメンバー名が消えている(以下はメンバー一覧から「にしかわ」を消した際の画像である)
<img width="301" alt="スクリーンショット 2022-11-25 131352" src="https://user-images.githubusercontent.com/110072048/203900001-43f78684-0b54-48f4-9093-fe047dfd70d1.png">

<img width="240" alt="スクリーンショット 2022-11-25 131409" src="https://user-images.githubusercontent.com/110072048/203900006-ea6948a4-ff37-4960-8df9-a14d782b1a9c.png">

# マージ前のチェックリスト

- [X] Issue に記載の DoD を満たしている
- [X] `yarn lint` の実行結果のスクリーンショットを添付している
<img width="516" alt="スクリーンショット 2022-11-25 120254" src="https://user-images.githubusercontent.com/110072048/203899504-9f00bebc-02ca-4ce9-be79-a50745979157.png">

# 補足

- MVP実装時のアプリのUIは[Wiki](https://github.com/OJT-3G/random-grouping-app/wiki/%E3%82%A2%E3%83%97%E3%83%AA%E3%81%AEUI)に記載してある。

- 下記についてはMVPの対応完了後に別issueで対応予定。
  * #27 
  * #17 
  * #16 
  * #25 
  * #30

2022-11-25 04:24 UTC, yk-nakamura requested changes

2022-11-25 04:24 UTC, yk-nakamura commented on pages/index.tsx
> +    members.splice(startOfDeleteMember, deleteCount)
好みの問題かもしれませんが、[filter](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/filter)を使う方が個人的には何を削除したいのかがわかりやすいかなーという気がしました。

2022-11-25 04:24 UTC, yk-nakamura commented on pages/index.tsx
> +                <th></th>
中身がないので`<th />`で良いと思います。
ぱっと見なんのためのタグなのかわからないので、コメントで削除ボタンの列とか分かるようにしておいてください。

2022-11-25 04:28 UTC, rknakashima commented on pages/index.tsx
> +    const deleteCount = 1
削除する人数は毎回必ず1人なので、`deleteCount` を宣言せず L.135, 136 で直接 1 を指定すればいいんじゃないかと思いました！

2022-11-25 04:29 UTC, RustyNail commented on pages/index.tsx
> +    const startOfDeleteRandomMembers = randomMembers.indexOf(deleteMember)
このネーミングどうでしょう？１年後の @tsubasa-nishikawa  さんが、見てわかりますかね？

2022-11-25 04:29 UTC, RustyNail commented on pages/index.tsx
> +    const deleteCount = 1
deleteCount = 1と実装したのは
deleteCount = 2となるケースが想定されている？
引数として、または渡す引数を変数として持つ必要があるのでしょうか？

2022-11-25 04:49 UTC, yk-nakamura commented on pages/index.tsx
> +    members.splice(startOfDeleteMember, deleteCount)
この修正はMUSTではない（西川さんなりに意図や信念があるのであればOK）です。

2022-11-25 04:50 UTC, RustyNail commented on pages/index.tsx
> +    const deleteCount = 1
同感です！
https://github.com/OJT-3G/random-grouping-app/pull/33#discussion_r1031995636

2022-11-25 04:52 UTC, RustyNail commented on pages/index.tsx
> +    const deleteCount = 1
あるいはdeleteCountを引数で扱い、デフォルト値を1にしておくなど。

2022-11-25 05:19 UTC, RustyNail commented
@tsubasa-nishikawa さん  
手元で動作見てみました。

![スクリーンショット 2022-11-25 14 16 07](https://user-images.githubusercontent.com/821981/203906209-2cb57bc4-c2dc-4a9a-ae3c-6958c8153e6c.png)

これはバグっているような。。
そもそもメンバー以上のグループ数指定はNGですよね？
削除を実装したことにより発生した事象ですね。対応が必要だと思います。

また、グループ数のメッセージも「0以上」では？

2022-11-25 06:59 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +    members.splice(startOfDeleteMember, deleteCount)
自分はこちらの画像の部分を参考にしました。
<img width="593" alt="スクリーンショット 2022-11-25 133110" src="https://user-images.githubusercontent.com/110072048/203920183-718d0d8d-2886-4cbc-aee5-ade59090757a.png">

filterを使うとなると指定の文字列を以外を取るために「!=」を使用するかと思います。個人的には「!=」を使わない書き方をしたいのでspliceでの実装をしたいと思います。

2022-11-25 08:28 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +                <th></th>
わかりやすくなるように修正しました。

[コミット内容](https://github.com/OJT-3G/random-grouping-app/pull/33/commits/595abb26e2e2ce327691372e17bc0a79d5ba3bbb)

2022-11-25 08:38 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +    const deleteCount = 1
直接1を代入しました。

[コミット内容](https://github.com/OJT-3G/random-grouping-app/pull/33/commits/a06b464fa8922a8d3d9239aa5717ae431b801c3b)

2022-11-25 08:39 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +    const startOfDeleteRandomMembers = randomMembers.indexOf(deleteMember)
startでなくindexであればわかると思ったので変更しました。

[コミット内容](https://github.com/OJT-3G/random-grouping-app/pull/33/commits/a06b464fa8922a8d3d9239aa5717ae431b801c3b)

2022-11-28 00:05 UTC, yk-nakamura commented on pages/index.tsx
> +                <th></th>
細かいですが`th`と`/`の間は半角スペースを入れてください

2022-11-28 00:10 UTC, yk-nakamura commented on pages/index.tsx
> +    members.splice(startOfDeleteMember, deleteCount)
なぜ`!=`を使いたくないかは理解できてない（対象の文字列以外のものを必要としているので、問題ないのでは？）ですが、spliceを使うということで承知しました。

2022-11-28 02:20 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +    const deleteCount = 1
[こちら](https://github.com/OJT-3G/random-grouping-app/pull/33#discussion_r1032124104)で対応した。

2022-11-28 02:24 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +          <input
1行が長い場合は改行するように自動整形が設定されており、それに合わせているのでこのままで開業した形でいきたいと思いました。

2022-11-28 05:16 UTC, tsubasa-nishikawa commented
コミットの「[メンバー数が0の時のメッセージが適切になるように、useEffectを用いて修正した](https://github.com/OJT-3G/random-grouping-app/pull/33/commits/f598e893d585ebc5c8f0c85e2fb6b1f4375726b2)」についてなのですが、正しくは「メンバー数を削除していくとグループ数より少なくなってもエラーが出ないバグの修正」になります。


@RustyNail さん、[こちら](https://github.com/OJT-3G/random-grouping-app/pull/33#issuecomment-1327031486)の投稿への返信です。
メンバー数を削除していくとグループ数より少なくなってもエラーが出ないバグの修正は[こちらのコミット](https://github.com/OJT-3G/random-grouping-app/pull/33/commits/f598e893d585ebc5c8f0c85e2fb6b1f4375726b2)で対応しました。画像のように問題なく表示されることも確認しました。
<img width="248" alt="スクリーンショット 2022-11-28 140034" src="https://user-images.githubusercontent.com/110072048/204199205-06dd0770-555e-4745-9d48-ed66f762bda2.png">
また、メンバー数が0の時には以下のようなメッセージが出るように[こちらのコミット](https://github.com/OJT-3G/random-grouping-app/pull/33/commits/b346f73c567176a6c57ec30e090d9cc1fbb4b7d9)で変更しました。
メンバー数が1以上の時は「(整数)以下」の表記で間違いはないです。
<img width="217" alt="スクリーンショット 2022-11-28 140009" src="https://user-images.githubusercontent.com/110072048/204199173-fcd2b0b7-ed2e-47b3-a312-46435df0bba6.png">

2022-11-28 10:23 UTC, RustyNail commented
エラーが発生します

https://user-images.githubusercontent.com/821981/204254046-1b735aae-777a-42fe-a416-740ef6d414ec.mov

2022-11-29 08:39 UTC, tsubasa-nishikawa commented
@RustyNail さん、[こちら](https://github.com/OJT-3G/random-grouping-app/pull/33#issuecomment-1328845500)の投稿への返信です。
メンバーが0人でエラーメッセージが出ている時はグループ数が入力できないようにしました。
その他にエラーが発生しないかは確認しました。

[コミット内容](https://github.com/OJT-3G/random-grouping-app/pull/33/commits/318818832a3b5d36934a57e10d59f9e439750793)

2022-11-29 22:29 UTC, RustyNail commented
> メンバーが0人でエラーメッセージが出ている時はグループ数が入力できないようにしました。

修正されていることを確認しました。



もう1点、不具合を見つけました。
削除の操作も関係しているので、今回の対応でデグレが生じた可能性があります。

メンバーを全て消すと、既存機能で提供されている「メンバー名入力 ＋ Enterキー押下」での追加ができなくなっています。
![スクリーンショット 2022-11-29 22 08 48](https://user-images.githubusercontent.com/821981/204537777-a7011798-90d7-4556-b274-d07d4cae7983.png)

2022-11-30 02:53 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +                <th></th>
半角スペースを入れました

2022-11-30 02:57 UTC, tsubasa-nishikawa commented
「メンバーが0人の時のメッセージ」がグループ数のところにあるのが適切ではないと判断し、こちらの[コミット内容](https://github.com/OJT-3G/random-grouping-app/pull/33/commits/cbddfd449b74e1e36355b51b6897940dcb145afd)にてエラーメッセージを追加のテキストボックスの上に持ってきました。

@RustyNail さん、[こちら](https://github.com/OJT-3G/random-grouping-app/pull/33#issuecomment-1331401909)のバグについて、上記のコミット内容によりバグが消えたので問題は解決しました。

2022-11-30 04:46 UTC, yk-nakamura commented on pages/index.tsx
> +                <th></th>
確認しましたが、どこで直したのか分かるようにコミットハッシュはってほしいです

2022-11-30 04:58 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +                <th></th>
こちらのコミットで対応しました。

[コミット内容](https://github.com/OJT-3G/random-grouping-app/pull/33/commits/b346f73c567176a6c57ec30e090d9cc1fbb4b7d9)

2022-11-30 06:59 UTC, RustyNail commented
@tsubasa-nishikawa  さん
上記のバグが解消されていることを確認しました。

ただ、以下のバグを見つけてしまいました。
名前未入力で追加しようとすると、メンバーの削除もグループ数の変更もできなくて
メンバーを追加しない限り他の操作が一切無効になってしまいます。
![スクリーンショット 2022-11-30 15 55 08](https://user-images.githubusercontent.com/821981/204728623-ab0a04f7-0c3b-4833-94d3-6104ae5937d4.png)

2022-11-30 07:00 UTC, RustyNail commented
@tsubasa-nishikawa 
上記のバグは同名エラーの時も同じです。


![スクリーンショット 2022-11-30 15 59 30](https://user-images.githubusercontent.com/821981/204728999-a15710b9-6293-459e-b3fe-7ffb9aa9cdad.png)

2022-11-30 07:28 UTC, tsubasa-nishikawa commented
[こちら](https://github.com/OJT-3G/random-grouping-app/pull/33#issuecomment-1331720246)と[こちら](https://github.com/OJT-3G/random-grouping-app/pull/33#issuecomment-1331721054)についてなのですが、バグではなく意図的に実装しました。
「エラーメッセージに指示があるときは他の操作をできないようにする事」でPOに整合を取ってあります([Teams](https://teams.microsoft.com/l/message/19:5e2e84fd47f64454b95c11b476a130ed@thread.tacv2/1669709453256?tenantId=e717ec3d-6036-4776-b72e-41f49481d91e&groupId=7a69bb74-23c5-4c3b-a99f-0129edcaf5e9&parentMessageId=1669709453256&teamName=2022%E5%B9%B4%E5%BA%A6%20RITS%20OJT(%E8%A5%BF%E6%97%A5%E6%9C%AC%E9%96%8B%E7%99%BAC)&channelName=%E8%A5%BF%E5%B7%9D%20%E7%BF%BC(%E9%87%91%E6%B2%A2%203G)&createdTime=1669709453256&allowXTenantAccess=false))

「エラーメッセージに指示があるときは他の操作をできないようにする事」とした理由はユーザーのエラー解消に役立てるための案として適切で、あわせてデグレも直せるためです。

2022-11-30 08:07 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +    members.splice(startOfDeleteMember, deleteCount)
個人的には「〇〇ではないとき」で書くよりも「〇〇なとき」で書いた方が見た人に伝わりやすいと思いました。
ただ、今回は「対象の文字列以外のものを必要としている」ので確かに「!=」を用いても良いかと思います。

どちらを使うかについてはMDNい合わせてspliceを使用しておきます。

2022-12-01 06:14 UTC, tsubasa-nishikawa commented
@RustyNail さん、お疲れ様です。
[こちら](https://github.com/OJT-3G/random-grouping-app/pull/33#issuecomment-1331744503)の投稿内容についてなのですが、「名前を入力してください」と「すでに存在する名前です、別の名前を入力してください」のエラーメッセージが出ている時は他の操作を無効化にしない方がユーザーにとって使いやすいと判断しPOに[受け入れ基準](https://github.com/OJT-3G/random-grouping-app/issues/5)の変更の確認を取ったので[こちら](https://github.com/OJT-3G/random-grouping-app/pull/33/commits/c7f4021a8ff54c759ddef7f69c28002a2702a4e8)のコミットで対応しました。
その他使いやすさを重視し二回ほどコミットしたので確認をお願いします。

その他の[コミット１](https://github.com/OJT-3G/random-grouping-app/pull/33/commits/40d019f0c4a519bfd8fbd5d9bec7403387563a10)，[コミット２](https://github.com/OJT-3G/random-grouping-app/pull/33/commits/6189b0f8829ff1a42b26833061537955a3f54f19)

2022-12-01 06:28 UTC, RustyNail commented on pages/index.tsx
> +    setErrorMessageOfAdditionalMember('')
@tsubasa-nishikawa 
L93.の下に書けばその後のif分で同じこと書かなくて良いのではないでしょうか？

> setErrorMessageOfAdditionalMember('')

つまり、if (lengthOfMembers === 0) {  のケースのみupdateする形で

2022-12-01 06:37 UTC, RustyNail commented on pages/index.tsx
> +import { ChangeEvent, KeyboardEvent, useEffect, useMemo, useState } from 'react'
キャメルケースで書くなら、統一して書かれた方が良いと思います。

2022-12-01 06:39 UTC, RustyNail commented on pages/index.tsx
> +        errorMessageOfAdditionalMember !==
ここはワンライナーでないとみにくくないですか？

2022-12-01 06:40 UTC, RustyNail commented on pages/index.tsx
> +        errorMessageOfAdditionalMember !==
というより、せめてすぐ上にある形とは揃えておいた方が良いと思います。
```
if ( errorMessageOfAdditionalMember !==
```

2022-12-01 06:50 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +import { ChangeEvent, KeyboardEvent, useEffect, useMemo, useState } from 'react'
単語の最初が小文字か大文字かで統一した方が良いという事でしょうか？

もしそうであれば、例えば'keyboardEvent'の最初を小文字にしたときは以下のエラーでます。
reactの方で定められてると思っていたのですが自分で名前を変更できるので変更した方が良い、という事でしょうか？

'keyboardEvent' という名前のエクスポートされたメンバーが '"react"' に含まれていません。候補: 'KeyboardEvent'ts(2724)

2022-12-01 06:53 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +        errorMessageOfAdditionalMember !==
自動整形でそうなってしまうのですが自動整形の一行の文字数設定を修正した方が良いのでしょうか？
自動整形の設定は開発者の中島さんには整合を取ってあります。

2022-12-01 06:56 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +    setErrorMessageOfAdditionalMember('')
確かにそちらの方が綺麗なコードですね。修正し操作に問題が無いことも確認しました。

[コミット内容](https://github.com/OJT-3G/random-grouping-app/pull/33/commits/ad0ece3460f545c2197f65627399e95afce84aeb)

2022-12-01 07:46 UTC, RustyNail commented on pages/index.tsx
> +import { ChangeEvent, KeyboardEvent, useEffect, useMemo, useState } from 'react'
あ、失礼しましたm_ _m
これはライブラリのimportということですね！？
だとしたら対応不要です

変数やfunctionの定義で自分で実装したケースであれば
キャメルケース、スネークケースなど統一して書くべきかと思ったのでコメントしました。

2022-12-01 07:49 UTC, RustyNail commented on pages/index.tsx
> +        errorMessageOfAdditionalMember !==
```
if () {
} {
}
```
の書き方がリンターに指摘されたということでしょうか？
であれば、リンターに従ってください。

そうではなく、自動整形で機械置換されたのであれば、あくまで読むのは開発者なので
なんでもかんでも機械で整形よりは読みやすいコードである方が望ましいと思います。 @tsubasa-nishikawa さん

2022-12-02 01:58 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +        errorMessageOfAdditionalMember !==
実業務では自動整形に合わせた書き方をするため、今回も自動整形に合わせた書き方をしたいです。
ただ、今のままでは確かに見にくいことと、条件式を何度も使用している部分があったので関数にしました。

[コミット内容](https://github.com/OJT-3G/random-grouping-app/pull/33/commits/2d109e26a1a5c53dba6c26335469fa1bdcd6f6b2)

2022-12-02 02:15 UTC, RustyNail commented on pages/index.tsx
> +    const judge = errorMessageOfAdditionalMember !== errorMessages.nameOfAdditionalMember.mustBeAdded
真偽値を返すだけなので変数定義不要では？

2022-12-02 02:15 UTC, RustyNail commented on pages/index.tsx
> +  const whetherMemberIsNecessary = () => {
関数名がわかりやすいものに工夫できそうです。
参考：https://qiita.com/munieru_jp/items/f66026060b7b5f0c3cbf

2022-12-02 02:47 UTC, RustyNail commented on pages/index.tsx
> +        errorMessageOfAdditionalMember !==
関数名について別でコメントしていますがリファクタもされていることを確認したので「Resolve conversation」ぽちリマス

2022-12-02 02:53 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +  const whetherMemberIsNecessary = () => {
ありがとうございます！
関数名についてなのですが、今回はメッセージが特定の内容であるかを判定しておりサイトにある
「中身が空か確認」「存在するか確認」「値を含むか確認」「～できるか」のどれに当てはまるかわかりませんでした。

「isMustBeAdded」が適切でしょうか？

2022-12-02 04:04 UTC, RustyNail commented on pages/index.tsx
> +  const whetherMemberIsNecessary = () => {
Teamsの方で回答済み

2022-12-02 04:05 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +  const whetherMemberIsNecessary = () => {
「メンバーがいない事を伝えるエラーメッセージが出ているか」で判定するのではなく「メンバーが存在するか」で判定するようにし、名前を「isExistMembers」に変更しました。確認をお願いします。

[コミット内容](https://github.com/OJT-3G/random-grouping-app/pull/33/commits/ed4058d7f609da204386bb9628ce3b0d8c53af25)

2022-12-02 04:13 UTC, RustyNail commented on pages/index.tsx
> +      if (isExistMembers()) {
isExistMembers() => trueのときerrorメッセージはなし
falseの時はメッセージあり
といった実装になるのでは？
現在は、どちらもtrueの条件をもつ実装しかないですが、実装は正しいです？

2022-12-02 04:25 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +      if (isExistMembers()) {
実装は正しいです！

外側のif文は「①追加したいメンバー名を入力するテキストボックスが空かどうか」で
内側のif文は「②メンバーが一人以上存在するか」を指しています

①がtrueで②もtrueの時はメンバーが存在しているので「名前を入力してください」のエラーメッセージで上書きされても問題がありません
①がtrueで②がfalseの時はメンバーがおらず全体的なエラーの要因となるので、先にメンバー追加をしてもらうためエラーメッセージの更新を行いません

2022-12-02 06:05 UTC, tsubasa-nishikawa commented on pages/index.tsx
> +      if (isExistMembers()) {
上記の件はTeamsの方でコードの説明をし、解決しました。
コードのif文の書き方を修正しました。確認をお願いします。

[コミット内容](https://github.com/OJT-3G/random-grouping-app/pull/33/commits/e002e16f2ab09fa68374eb1f59408b96c9d1a5e7)

2022-12-02 07:16 UTC, RustyNail approved these changes
LGTM

2022-12-02 07:21 UTC, yk-nakamura approved these changes
LGTMです

2022-12-02 08:02 UTC, merged