「yarn dev」でエラーが出たためファイル名とコードの修正を行った
OJT-3G/random-grouping-app pull request #50
Opened 2022-12-07 02:23 UTC by tsubasa-nishikawa

- Resolve #48
- 希望納期:12/7
- レビュアー: @rknakashima @yk-nakamura @RustyNail
- 仕様書: 無し

# 対応内容

- babelのファイル名とコード内容を変更し、エラーを解消した

# 動作確認内容

## 受入テストの項目

1.babelの導入によるエラーの対応であるため無し

# マージ前のチェックリスト

- [X] Issue に記載の DoD を満たしている
- [X] `yarn dev` を実行した後ローカルホスト画面でエラーが出ない
- [X] `yarn lint` の実行結果のスクリーンショットを添付している
<img width="535" alt="image" src="https://user-images.githubusercontent.com/110072048/206071052-36fd5927-0ad7-481e-a61c-003c30b1e317.png">
- [X] `yarn test` の実行結果のスクリーンショットを添付している
<img width="541" alt="image" src="https://user-images.githubusercontent.com/110072048/206071949-f7716a3b-e605-41f2-bc74-2ca19fa97702.png">

# 補足

- MVP実装時のアプリのUIは[Wiki](https://github.com/OJT-3G/random-grouping-app/wiki/%E3%82%A2%E3%83%97%E3%83%AA%E3%81%AEUI)に記載してある。

- 下記についてはMVPの対応完了後に別issueで対応予定。
  * #27 
  * #17 
  * #16 
  * #25 
  * #30

2022-12-07 02:26 UTC, tsubasa-nishikawa commented
エラー修正用のブランチを切り忘れてプッシュしてしまったため、ブランチ名が「feature/test-creation」となってしまっています。申し訳ございません。

2022-12-07 02:46 UTC, yk-nakamura requested changes
なぜこの変更内容でエラーが解消したのでしょうか？
そのあたりの説明がないと、レビュアーは変更が適切なのかどうか判断しづらいかなと思いました。

また、今回はアプリの実装の変更ではないため、説明欄に記載の「補足」が内容にあっていません。
とにかくコピペすれば良いというわけではなく、取捨選択をしましょう。

2022-12-07 02:46 UTC, yk-nakamura commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] `yarn dev` を実行した後ローカルホスト画面でエラーが出ない
プルリクタイトルや対応内容にもテンプレートを変更した旨の記載をお願いします。

2022-12-07 02:46 UTC, rknakashima commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] `yarn dev` を実行した後ローカルホスト画面でエラーが出ない
ローカルホスト画面でエラーが出ない ってどういう状態でしょうか？
ブラウザのコンソールにエラーが出ていない状態なのか、アプリが起動して使える状態(アプリの画面にエラーが表示されていない)なのか、もっと別のことを表しているかがこの文から分からなかったです。

2022-12-07 04:59 UTC, tsubasa-nishikawa commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] `yarn dev` を実行した後ローカルホスト画面でエラーが出ない
```
なぜこの変更内容でエラーが解消したのでしょうか？
そのあたりの説明がないと、レビュアーは変更が適切なのかどうか判断しづらいかなと思いました。
```
エラーの原因と対応内容が抜けていたので記載しました。コーチャーにTeamsで確認しているので内容は変わるかもしれないです。変更があった際にはこちらの返信で報告します。

```
また、今回はアプリの実装の変更ではないため、説明欄に記載の「補足」と変更内容が合っていません。
とにかくコピペすれば良いというわけではなく、取捨選択をしましょう。
```

今回はエラーの解消が目的であるため補足の内容は不要ということですね、消しました。

プルリクエストのタイトルと内容にテンプレート変更の内容が無かったので記載しました。

2022-12-07 05:03 UTC, tsubasa-nishikawa commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] `yarn dev` を実行した後ローカルホスト画面でエラーが出ない
わかりづらい書き方になっていたので「`yarn dev` でアプリ画面にエラーが出ず、アプリが使用できる」に変更しました

[コミット内容](https://github.com/OJT-3G/random-grouping-app/pull/50/commits/7371ab73bfd43743964c48ee5450fdc9d1d4c2bd)

2022-12-07 05:28 UTC, yk-nakamura commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] `yarn dev` を実行した後ローカルホスト画面でエラーが出ない
修正ありがとうございます。
なんとなく、原因と対応を見るとファイル名の変更もいらないのかな？という気がしましたが、ファイル名変更も必要だったんでしょうか？

2022-12-07 06:23 UTC, tsubasa-nishikawa commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] `yarn dev` を実行した後ローカルホスト画面でエラーが出ない
対応内容を修正しました。
今の書き方でファイルの形式の変更が必要であったことが伝わるでしょうか？

2022-12-07 06:54 UTC, yk-nakamura commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] `yarn dev` を実行した後ローカルホスト画面でエラーが出ない
うーん。。いまいちファイル形式を変えないといけない理由が理解できていません。
https://nextjs-ja-translation-docs.vercel.app/docs/advanced-features/customizing-babel-config これ見た限りでは`babel.config.js`でも良いのでは？
https://babeljs.io/docs/en/config-files#configuration-file-types によると、`babelrc`と`babel.config`の違いはスコープだけのように読み取れます。
単にプリセットの指定が誤っていた（next.js用の設定になっていなかった）だけで、ファイル名は関係ないのではないでしょうか？

また、babelrcはXMLファイルではない気がします。中身はJSONフォーマットですよね？

2022-12-07 06:56 UTC, yk-nakamura commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] `yarn dev` を実行した後ローカルホスト画面でエラーが出ない
記載の通り

> JavaScriptからXMLファイルへ変更
> 隠しファイルに変更

が必要だったとして、なぜこの変更をするとエラーが解消するのですか？

2022-12-07 08:09 UTC, yk-nakamura commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] `yarn dev` を実行した後ローカルホスト画面でエラーが出ない
時間かかりそうだったので手元で試しました。

下記のbabel.config.jsでも問題なく動作します。
```
module.exports = {
  presets: ['next/babel'],
}
```
JSON形式で書きたいのであれば、babel.config.**json**でも良いです。

今回は開発テーマでの設定を参考にするところから始めたので、それに引っ張られたという事情はあると思いますが、
「エラーが解消できたからOK」ではなく、自分の変更に責任を持って
`babelrcとは何か？` `babel.config.jsではなぜダメなのか？` `公式ではどのように設定するように指示があるのか？`
などを理解したうえで変更を行なうようにしてほしいです。

どちらでも動くということはわかったので、西川さんなりの考えを持ってどちらかを選択してください。

2022-12-07 08:24 UTC, tsubasa-nishikawa commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] `yarn dev` を実行した後ローカルホスト画面でエラーが出ない
>単にプリセットの指定が誤っていた（next.js用の設定になっていなかった）だけで、ファイル名は関係ないのではないでしょうか？

コードの中身を変えずにファイル名をいくつか変更してファイル名の変更が必要であることを確認しました。
・「.babelrc」→問題なし
・「.babel」→以下のエラーが出る
・「.babel.config」→以下のエラーが出る

```
$ yarn test
yarn run v1.22.19
$ jest
 FAIL  test/index.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.        
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    C:\Users\r23600282\random-grouping-app\test\index.test.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { 
describe, it } from '@jest/globals';
                                                                                      ^^^^^^   

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1449:14)       

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.555 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
＞また、babelrcはXMLファイルではない気がします。中身はJSONフォーマットですよね？

XMLはマークアップ言語であり、今回はJavaScriptにおける表記法を応用した文字形式のファイルであるのでJSONフォーマットである事、調べて理解しました。

＞記載の通り
```
JavaScriptからXMLファイルへ変更
隠しファイルに変更
```
が必要だったとして、なぜこの変更をするとエラーが解消するのですか？

プリセットの定義がJSONフォーマットに沿った書き方であるのに対してファイルがJavaScriptになってるとエラーが出るので、ファイルの名前変更を行いJSONフォーマットに変更した、と思っていました。

2022-12-07 08:32 UTC, tsubasa-nishikawa commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] `yarn dev` を実行した後ローカルホスト画面でエラーが出ない
[こちらの内容](https://github.com/OJT-3G/random-grouping-app/pull/50#discussion_r1041883933)への返信です。
確認ありがとうございます。

開発テーマでの設定に引っ張られJSでの記載を行う事を選択肢から外してしまっていました。
どちらにするかは公式サイトを見てから決めたいと思います。

2022-12-07 08:53 UTC, tsubasa-nishikawa commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] `yarn dev` を実行した後ローカルホスト画面でエラーが出ない
https://babeljs.io/
ここが公式サイトになるのかなと思ったのですが見方がわかりませんでした...
乗っけていただいたサイトや、いくつかのサイト(Qiita)を見てみたらJSON形式で書かれているところが多いので一般的な書き方に合わせるためJSON形式で書こうと思います。ただ、「babel.config」から「babelrc」に変更する理由はないのでそこだけは戻しておきました。確認をお願いします。

[コミット内容](https://github.com/OJT-3G/random-grouping-app/pull/50/commits/7371ab73bfd43743964c48ee5450fdc9d1d4c2bd)

2022-12-07 23:12 UTC, yk-nakamura commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] `yarn dev` を実行した後ローカルホスト画面でエラーが出ない
> コードの中身を変えずにファイル名をいくつか変更してファイル名の変更が必要であることを確認しました。
・「.babelrc」→問題なし
・「.babel」→以下のエラーが出る
・「.babel.config」→以下のエラーが出る

設定ファイル名として何が適切なのかを調べずに、手当たり次第ファイル名変更して試してたってことですかね。
https://babeljs.io/docs/en/config-files#configuration-file-types を見れば、使用できるファイル名・形式がちゃんと明記されています。
こういう調査が必要なタスクについては他のメンバーも正解を知らないことが多いので、担当者が十分理解せずに進めることでチームメンバー全体の理解が誤ったものになってしまう可能性があります。
前のコメントでも書きましたが、できる限り変更の裏付けをとり、情報が見つからないのであれば他のメンバーに相談するなど、いい加減な対応にならないよう今後は気をつけましょう。

"JSON形式の情報のほうが多いので今回はJSONを採用"ということで承知しました。
対応内容の記載も良くなったと思いますが、上記のJSONを採用した理由も書いておきましょうか。
また、https://github.com/OJT-3G/random-grouping-app/pull/50#discussion_r1041924499 のコミットのリンクが違うみたいなので、ご確認お願いします。

2022-12-08 00:58 UTC, tsubasa-nishikawa commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] `yarn dev` を実行した後ローカルホスト画面でエラーが出ない
>設定ファイル名として何が適切なのかを調べずに、手当たり次第ファイル名変更して試してたってことですかね。
https://babeljs.io/docs/en/config-files#configuration-file-types を見れば、使用できるファイル名・形式がちゃんと明記されています。

手あたり次第調べていました…サイトもそちらの方はしっかり見れていませんでした。

>前のコメントでも書きましたが、できる限り変更の裏付けをとり、情報が見つからないのであれば他のメンバーに相談するなど、いい加減な対応にならないよう今後は気をつけましょう。

変更には裏付けを必ずとる事、情報がどこにあるかは開発メンバーに相談する事、今後気を付けます。

＞「JSON形式の情報ほうが多いので今回はJSONを採用」ということで 承知
しました。https://github.com/OJT-3G/random-grouping-app/pull/50#discussion_r1041924499のコミットのリンクが違うみたいなので、ご確認お願いします。

コミット内容の先を間違えてました！いかになります。
[コミット内容](https://github.com/OJT-3G/random-grouping-app/pull/50/commits/f417238d0364376690f8d49ee493294e08d3ba12)

2022-12-08 01:00 UTC, yk-nakamura commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] `yarn dev` を実行した後ローカルホスト画面でエラーが出ない
修正確認しました。ありがとうございます。

2022-12-08 01:01 UTC, tsubasa-nishikawa commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] `yarn dev` を実行した後ローカルホスト画面でエラーが出ない
>設定ファイル名として何が適切なのかを調べずに、手当たり次第ファイル名変更して試してたってことですかね。
https://babeljs.io/docs/en/config-files#configuration-file-types を見れば、使用できるファイル名・形式がちゃんと明記されています。

手あたり次第調べていました…サイトもそちらの方はしっかり見れていませんでした。

>前のコメントでも書きましたが、できる限り変更の裏付けをとり、情報が見つからないのであれば他のメンバーに相談するなど、いい加減な対応にならないよう今後は気をつけましょう。

変更には裏付けを必ずとる事、情報がどこにあるかは開発メンバーに相談する事、今後気を付けます。

＞https://github.com/OJT-3G/random-grouping-app/pull/50#discussion_r1041924499のコミットのリンクが違うみたいなので、ご確認お願いします。

コミット内容の先を間違えてました！以下になります。
[コミット内容](https://github.com/OJT-3G/random-grouping-app/pull/50/commits/f417238d0364376690f8d49ee493294e08d3ba12)

2022-12-08 01:01 UTC, yk-nakamura approved these changes
LGTM

2022-12-08 01:01 UTC, merged